# Generated by Django 3.2.3 on 2022-04-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eunit', models.CharField(max_length=64)),
                ('Elesson', models.CharField(max_length=64)),
                ('Epoem', models.CharField(max_length=64)),
                ('Eobj', models.CharField(max_length=64)),
            ],
        ),
    ]
